#pragma once
#define WORLD_WIDTH    32
#define WORLD_HEIGHT  4 // worold_level
#define AIR 0
#define BLOCK 1
#define TILE_SIZE  4

uint8_t world[WORLD_HEIGHT][WORLD_WIDTH]={
{BLOCK, BLOCK, AIR, AIR, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK},
{BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK},
{BLOCK, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK},
{BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK},
};

uint8_t world1[WORLD_HEIGHT][WORLD_WIDTH] = {
{AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, AIR, BLOCK, BLOCK, AIR, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, AIR, BLOCK, BLOCK, BLOCK, AIR, BLOCK, BLOCK, BLOCK, BLOCK},
{BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK},
{AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, AIR},
{BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK},
};

uint8_t world2[WORLD_HEIGHT][WORLD_WIDTH] = {
{BLOCK, BLOCK, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK},
{BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR, AIR, AIR, AIR, BLOCK, BLOCK, AIR, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK},
{BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK},
{BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK},
};

uint8_t world3[WORLD_HEIGHT][WORLD_WIDTH]={
{AIR, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK},
{AIR, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR, BLOCK, BLOCK},
{AIR, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, AIR, AIR, AIR},
{BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK},
};
